#!/bin/bash
# chain_template -- TEMPLATE FOR: generate a ROOT macro to combine the result TTrees from a local batch run
# Usage: chain_template.sh
# -- Run this script in the umbrella directory of your datarun
# ~ Mark J. Duvall ~ mjduvall@hawaii.edu ~ 10/2022 ~ #


##Copyright (C) 2021 Mark J. Duvall
##
##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# init
DATARUN_AUTO=$(basename $(pwd))
DATARUN=${1:-$DATARUN_AUTO}
OUTFILE="$DATARUN"_ex.root

# create chains.cxx
echo -e "\
// chain.cxx -- combine TChains
// Generated by user $USER on host $HOSTNAME at $(date -R)\n
void chain() {\n
// init
TChain ch(\"T_ex\");\n\n// file loop\n" > chain_template.cxx

# add individual runs
for DIR in $DATARUN*/; do
  FILE_BASE=$(basename $DIR /)
  FILE_PREFIX="$FILE_BASE/$FILE_BASE"
  FILENAME=$FILE_PREFIX"_ex.root"
  echo "\
ch.Add(\"$FILE_BASE/$FILENAME\");
TTree* t = (TTree*)ch.GetFile()->FindObjectAny(\"T_ex\");
// extract any other desired object here
"  >> chain_template.cxx
done

# prepare merging and saving
echo -e "\
// merge trees
ch.Merge(\"$OUTFILE\");
TFile* f = TFile::Open(\"$OUTFILE\", \"update\");
f->Save();
f->Close();\n
//all pau!   )
}" >> chain_template.cxx

# run the newly-created macro
root -q -l -b 'chain_template.cxx()'

# all pau!  )
exit 0
