#!/bin/bash
# cvim -- conveniently open C++ classes in vim tabs
# USAGE: cvim [-h|-r] <NAME>
# Suggestion: add the following line to your ~/.bash_aliases:
#   alias cview='cvim -r'
# ~ Mark J. Duvall ~ duvall3.git@gmail.com ~ 06/2023 ~ #

# Copyright (C) 2023 Mark J. Duvall / T. Rocks Science
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 


## INIT

# general
NULL=/dev/null
ERR=/dev/stderr

# control for aliases
ECHO="$(which echo) -e"

# define usage
usage() {
  $ECHO "Usage: cvim [-h|-r] <NAME>"
  $ECHO "conveniently open C++ classes in vim tabs"
  $ECHO
  $ECHO "Options:"
  $ECHO "  -h\tShow this help message and exit"
  $ECHO "  -r\tOpen file(s) in read-only mode"
  $ECHO
}

# process options
declare VIMOPTS
while getopts "hr" OPTIONS; do
  case $OPTIONS in
    h)
      usage
      exit 10
      ;;
    r)
      VIMOPTS="-R"
      ;;
    *)
      $ECHO
      usage
      exit 11
      ;;
  esac
done
shift $((OPTIND-1)) # uncomment for options with args


## MAIN

# # dir check
# if [[ $(pwd) =~ [Pp](ublic|rivate) ]]; then
#   FIND_PATH=".."
# else
#   FIND_PATH="."
# fi

# dir check
HEADER_PATH="."
SOURCE_PATH="."
ORIG_DIR=$(pwd)
if [[ $ORIG_DIR =~ [Pp](ublic|rivate) ]]; then cd ..; fi
HEADER_PATH+=" $(find -maxdepth 1 -iname public)"
SOURCE_PATH+=" $(find -maxdepth 1 -iname private)"

# locate header and source files
CLASS=$(basename ${1%.*})
# HEADER=$(find $FIND_PATH -name "$CLASS.h*")
# SOURCE=$(find $FIND_PATH -name "$CLASS.c*")
HEADER=( $(find $HEADER_PATH -maxdepth 1 -regextype egrep -iregex ".*$CLASS\.h(h|pp)?") )
SOURCE=( $(find $SOURCE_PATH -maxdepth 1 -regextype egrep -iregex ".*$CLASS\.c(c|pp|xx)?") )
# echo -e "Class:\t$CLASS\nHeader:\t${HEADER[*]}\nSource:\t${SOURCE[*]}" #debug

# confirm
N_HEADERS=${#HEADER[*]}
# check header(s)
if [ $N_HEADERS -eq 0 ]; then
  echo "Warning: No header files for \"$1\" found." > $ERR
elif [ $N_HEADERS -gt 1 ]; then
  echo "Warning: Multiple header files for \"$1\" found: ${HEADER[*]}; using first item." > $ERR
  HEADER=${HEADER[0]}
fi
# check source(s)
N_SOURCES=${#SOURCE[*]}
if [ $N_SOURCES -eq 0 ]; then
  echo "Warning: No source files for \"$1\" found." > $ERR
elif [ $N_SOURCES -gt 1 ]; then
  echo "Warning: Multiple source files for \"$1\" found: ${SOURCE[*]}; using first item." > $ERR
  SOURCE=${SOURCE[0]}
fi
# exit if nothing found
if [ $N_HEADERS -eq 0 ] && [ $N_SOURCES -eq 0 ]; then
  echo "ERROR: No header or source files for \"$1\" found. Exitig." > $ERR
  exit 5
fi

# open file(s)
# echo -e "Class:\t$CLASS\nHeader:\t$HEADER\nSource:\t$SOURCE" #debug
vim -p $VIMOPTS $HEADER $VIMOPTS $SOURCE


## EXIT

# all pau!   )
EXIT_STATUS=${EXIT_STATUS:-0}
exit $EXIT_STATUS

