#!/bin/bash
# cvim -- conveniently open C++ classes in vim tabs
# USAGE: cvim [-h|-r] <NAME>
# Suggestion: add the following line to your ~/.bash_aliases:
#   alias cview='cvim -r'
# ~ Mark J. Duvall ~ duvall3.git@gmail.com ~ 06/2023 ~ #

# Copyright (C) 2023 Mark J. Duvall / T. Rocks Science
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 


## INIT

# general
NULL=/dev/null
ERR=/dev/stderr

# control for aliases
ECHO="$(which echo) -e"

# define usage
usage() {
  $ECHO "Usage: cvim [-h|-r] <NAME>"
  $ECHO "conveniently open C++ classes in vim tabs"
  $ECHO
  $ECHO "Options:"
  $ECHO "  -h\tShow this help message and exit"
  $ECHO "  -r\tOpen file(s) in read-only mode"
  $ECHO
}

# process options
declare VIMOPTS
while getopts "hr" OPTIONS; do
  case $OPTIONS in
    h)
      usage
      exit 10
      ;;
    r)
      VIMOPTS="-R"
      ;;
    *)
      $ECHO
      usage
      exit 11
      ;;
  esac
done
shift $((OPTIND-1)) # uncomment for options with args


## MAIN

# dir check
if [[ $(pwd) =~ [Pp](ublic|rivate) ]]; then
  FIND_PATH=".."
else
  FIND_PATH="."
fi

# locate header and source files
CLASS=$(basename ${1%.*})
HEADER=$(find $FIND_PATH -name "$CLASS.h*")
SOURCE=$(find $FIND_PATH -name "$CLASS.c*")
# echo -e "Class:\t$CLASS\nHeader:\t$HEADER\nSource:\t$SOURCE" #debug

# confirm
HEADER_MISSING=false
SOURCE_MISSING=false
if [[ ! -e $HEADER ]]; then
  HEADER_MISSING=true
  echo "Warning: Header for $1 not found."
fi
if [[ ! -e $SOURCE ]]; then
  SOURCE_MISSING=true
  echo "Warning: Source for $1 not found."
fi
if ( $HEADER_MISSING && $SOURCE_MISSING ); then
  echo "Error in cvim: No files for $1 found. Exiting."
  exit 1
fi

# open file(s)
# echo -e "Class:\t$CLASS\nHeader:\t$HEADER\nSource:\t$SOURCE" #debug
vim -p $VIMOPTS $HEADER $VIMOPTS $SOURCE

# all pau!   )
exit $?



## EXIT

# all pau!   )
EXIT_STATUS=${EXIT_STATUS:-0}
exit $EXIT_STATUS

