#!/bin/bash
# exportRATmodel -- Export a 3D model of the current RAT-PAC experiment's geometry to VRML2 and (optionally) convert to X3D
# Notes:
# -- Run this script in the experiment directory (typically $GLG4DATA/<EXPERIMENT_NAME>; for example, "~/rat-pac/data/miniTimeCube/").
# ## -- Like RAT-PAC, this script assumes that the current directory contains either a macro or a symlink
# ##      located at "./prerun.mac", containing (or calling another macro containing) the /rat/db/set commands for "DETECTOR experiment"
# ##      and "DETECTOR geo_file". If such a "prerun.mac" is not present in your experiment's directory, use the "-p" option
# ##      to supply the location of such a macro.
# -- The X3D conversion is performed by the (open-source, multi-platform) program
#      "view3dscene" (https://castle-engine.sourceforge.io/view3dscene.php),
#      so this program is required if the conversion flag is set.
# -- Your installation of RAT-PAC must have VRML2 support; check your version's output for the line "VRML2FILE (VRML2FILE)" under
#      the line "Current available graphics systems are:".
# USAGE: exportRATmodel [-h|-x] 
# ~ Mark J. Duvall ~ duvall3.git@gmail.com ~ 06/2023 ~ #

# Copyright (C) 2023 Mark J. Duvall / T. Rocks Science
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 


## INIT

# general
NULL=/dev/null
ERR=/dev/stderr
VRML_MACRO="exportVRML.mac"
INITIAL_LATEST_WRL=$('ls' -tr1 *.wrl 2> $NULL | 'tail' -n 1)
INITIAL_LATEST_WRL=${INITIAL_LATEST_WRL:-"none"}

# prog check and control for aliases
HAS_VIEW3DSCENE=false
ECHO="$(which echo) -e"
CAT=$(which cat)
RAT="$(which rat 2> $NULL) -l $NULL"
VIEW3DSCENE=$(which view3dscene 2> $NULL)
if [ $VIEW3DSCENE ]; then
  HAS_VIEW3DSCENE=true
  CONVERTER=$(which tovrmlx3d)
fi

# define usage
usage() {
  $ECHO "Usage: exportRATmodel [-h|-x] "
  $ECHO "Export a 3D model of the current RAT-PAC experiment's geometry to VRML2 and (optionally) convert to X3D"
  $ECHO
  $ECHO "Options:"
  $ECHO "  -h\tShow this help message and exit"
  $ECHO "  -x\tConvert VRML output file to X3D format"
  $ECHO
}

# process options
DO_X3D=false
while getopts "hx" OPTIONS; do
  case $OPTIONS in
    h)
      usage
      exit 10
      ;;
    x)
      DO_X3D=true
      ;;
    *)
      $ECHO
      usage
      exit 11
      ;;
  esac
done
# shift $((OPTIND-1)) # uncomment for options with args


## MAIN

# create vrml macro
declare MACRO_STR
MACRO_STR+="/control/execute prerun.mac\n"
MACRO_STR+="/vis/open VRML2FILE\n"
MACRO_STR+="/vis/scene/create\n"
MACRO_STR+="/vis/drawVolume\n"
MACRO_STR+="/vis/viewer/flush\n"
$ECHO $MACRO_STR > $VRML_MACRO

# run rat with vrml macro
IS_NEW_WRL=false
$RAT $VRML_MACRO 2>&1 > $NULL | $CAT
$ECHO
# EXIT_STATUS=$?		#DISABLED: rat always exits (crashes) with a segfault if initializing but never calling /run/beamOn
FINAL_LATEST_WRL=$('ls' -tr1 *.wrl | 'tail' -n 1)
if [ $INITIAL_LATEST_WRL = $FINAL_LATEST_WRL ]; then
  $ECHO "Warning: No new .wrl file detected." > $ERR
  EXIT_STATUS=5
else
  $ECHO "Exported geometry written to $FINAL_LATEST_WRL"
  IS_NEW_WRL=true
fi

# convert if desired
if $DO_X3D; then
  if ! $HAS_VIEW3DSCENE; then
    $ECHO "Conversion error: Program \"view3dscene\" missing. See comments in this script. Try 'sudo apt install view3dscene' if on Ubuntu/Debian, or contact your system administrator." > $ERR
    EXIT_STATUS=3
  else
    # perform conversion
    if $IS_NEW_WRL; then
      OUTFILE_X3D=${FINAL_LATEST_WRL%wrl}x3d
      $CONVERTER --encoding=xml $FINAL_LATEST_WRL > $OUTFILE_X3D
      EXIT_STATUS=$?
      if [ $EXIT_STATUS -eq 0 ]; then $ECHO "Exported geometry converted to $OUTFILE_X3D"; fi
    fi
  fi
fi


## EXIT

# all pau!   )
EXIT_STATUS=${EXIT_STATUS:-0}
if [ $EXIT_STATUS -eq 0 ]; then
  $ECHO 'Geometry export completed! (Ignore the segfault from RAT).'
  if $HAS_VIEW3DSCENE; then $ECHO "You can now view the output file(s) using \"view3dscene <FILE>\"."; fi
fi
exit $EXIT_STATUS

