#!/bin/bash
# fix_COMPMAIN_glbox -- silly script to prepare copy/paste commands
#   for fixing COMPMAIN's glbox plots interactively
# ~ Mark J. Duvall ~ mjduvall@hawaii.edu ~ 9/2021 ~ #

##Copyright (C) 2021 Mark J. Duvall
##
##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <http://www.gnu.org/licenses/>.

## init
RESULTS_DIR=$RATROOT/data/COMPMAIN_RESULTS/ROOT_files
OUTPUT_FILE=$RATROOT/user/shell_scripts/fix_COMPMAIN_glbox.txt
EXIT_STATS=()
echo -e "###   $(basename $OUTPUT_FILE)   ###\n# ~ generated by $USER on $HOSTNAME at $(date -R) ~ #\n" > $OUTPUT_FILE

## MAIN

for LINK in $RESULTS_DIR/*_results.root; do

  # datarun init
  FILE=$(readlink $LINK)
  FILE_NAME=$(basename $FILE)
  DATARUN_DIR=$(dirname $FILE)
  DATARUN_NAME=$(basename $FILE _results.root)
  EXPERIMENT=$(echo $FILE | /usr/bin/grep -iEo ".*/data/[[:alnum:]-]+" | awk -F / '{print $NF}')
  XYZ_FILENAME="$DATARUN_NAME"_pd-xyz.png
  XYZ_GEO_FILENAME="$DATARUN_NAME"_pd-xyz-with-geo.png

#  # c3 plots
#  echo -e "
#cd $DATARUN_DIR
#root $FILE_NAME
#c3->Draw();
#c3->Print(\"$XYZ_FILENAME\");
#c3->Close();
#gFile->Close();" >> $OUTPUT_FILE

  # c3 plots
  echo -e "
cd $DATARUN_DIR
root rootcommands.cxx" >> $OUTPUT_FILE

  # c3_with-geo plots
  case $EXPERIMENT in
    chooz)
      echo -e "const char* resultsFilename = \"$FILE_NAME\"\n.x addGeoChooz.cxx" >> $OUTPUT_FILE
      ;;
    santa)
      echo -e "TList *vols = addGeoSANTA(\"$DATARUN_NAME"_0"/$DATARUN_NAME"_0"/$DATARUN_NAME"_0.root"\", \"$FILE_NAME\");" >> $OUTPUT_FILE
      ;;
    nulat*|*-3d*)
      echo -e "TList *vols = addGeoNuLat(\"$DATARUN_NAME"_0"/$DATARUN_NAME"_0"/$DATARUN_NAME"_0.root"\", \"$FILE_NAME\");" >> $OUTPUT_FILE
      if [[ $EXPERIMENT =~ checkerboard && ! $EXPERIMENT =~ .*-ref ]]; then echo -e "toggleInertVisAddGeo(vols);" >> $OUTPUT_FILE; fi
      ;;
    sandd|*-2d*|*-ref)
      echo -e "TList *vols = addGeoSANDD(\"$DATARUN_NAME"_0"/$DATARUN_NAME"_0"/$DATARUN_NAME"_0.root"\", \"$FILE_NAME\");" >> $OUTPUT_FILE
      if [[ $EXPERIMENT =~ checkerboard && ! $EXPERIMENT =~ .*-ref ]]; then echo -e "toggleInertVisAddGeo(vols, 2);" >> $OUTPUT_FILE; fi
      ;;
    *)
      echo -e "WARNING: Experiment \"$EXPERIMENT\" not recognized among pre-defined types. Proceeding with remaining results files."
      ;;
  esac
  echo -e "\
TView3D *view = gPad->GetView();" >> $OUTPUT_FILE
if [[ $EXPERIMENT =~ chooz ]]; then echo -n "//" >> $OUTPUT_FILE; fi
echo -e "view->SetParallel();
view->ShowAxis();
view->Draw();
c3->Print(\"$XYZ_GEO_FILENAME\");
c3->Close();
gFile->Close();
.q" >> $OUTPUT_FILE
    
  EXIT_STATS=(${EXIT_STATS[*]} $?)

done

echo -e "\ncd $RATROOT/data/COMPMAIN_RESULTS\nupdate_COMPMAIN_links.sh\n" >> $OUTPUT_FILE

## return and report status
cd $ORIG_DIR
if [[ $(( $(echo ${EXIT_STATS[*]} | tr " " "+") )) -gt 0 ]]; then
  echo -e "Plot-fixing prepared, with errors.\nExit statuses:"
  k=0
  column -t <(
  for LINK in $RESULTS_DIR/*; do
    echo -e $LINK "\t" ${EXIT_STATS[k]} "\n"
    ((k++))
  done
  NUM_STATS=${#EXIT_STATS[*]}
  echo -e "update_COMPMAIN_results.sh\t${EXIT_STATS[$NUM_STATS-1]}"
  )
  exit 2
else
  echo -e "\nPlot-fixing prepared!\n"
  exit 0
fi
## all pau!   )
