#!/bin/bash
# plot_gammas_mfile -- generate m-file for making total & agent-specific plots of gamma multiplicities & energy totals
# ~ Mark J. Duvall ~ mjduvall@hawaii.edu ~ August 2015 ~ #



## read in data
DATARUN=$(dirname $(pwd))
echo "\
  % plot_gammas -- generate histograms for gamma multiplicity & total energy (at capture) for each capturing agent
  % 	-- generated by ${BASH_SOURCE[0]} for $DATARUN; $(date)
  
  
  %% TOTAL PLOTS
  % read in data & prepare histograms
  data = dlmread( \'$DATARUN.txt\', \'\', 1, 0 );
  g_mult = data(:,8);
  g_ke = data(:,9);
  mult = [0:15]; % multiplicity bins (0--15 by integers)
  h_g_mult = hist( g_mult, mult );
  E = [0:.01:10]; % energy bins
  h_g_ke = hist( g_ke, E ); (0--10MeV by 10keV)
  
  % prepare figures:
  % multiplicity plot
  f_mult = figure('position', [1000 100 1.5*[560 420]]);
  ax_mult = axes;
  xla_mult = xlabel('Multiplicity');
  T_mult = title('Gamma Multiplicities for $(dirname $(pwd))');
  % energy plot
  f_ke = figure('position', [1000 100 1.5*[560 420]]);
  ax_ke = axes('yscale', 'log');
  xla_ke = xlabel('Energy (MeV)');
  T_ke = title('Total Energy of Capture Gammas for $(dirname $(pwd))');
  
  % make plots
  s_mult = stairs( ax_mult, mult, h_g_mult );
  s_g_ke = stairs( ax_ke, E, h_g_ke );
  set(ax_ke, 'yscale', 'log')
  
  
" > ./plot_gammas.m



## get data for each capture agent
for agent_file in ./gam/*.gam; do
  
  agent=$(basename $agent_file .gam)
  
  echo "\
    %% INDIVIDUAL PLOTS
    % read in data
    data = dlmread( \'$agent_file\', \'\', 0, 1 );
    
    % create lists from \"data\"
    g_mult_$agent = data(:,1);   % can remove individual labels (& overwrite each time) if RAM becomes an issue
    g_ke_$agent = data(:,2);  % can remove individual labels (& overwrite each time) if RAM becomes an issue
%   clear data


" >> ./plot_gammas.m

done



## plot multiplicities
for agent_file in ./gam/*.gam; do
  
  agent=$(basename $agent_file .gam)

  echo "\
    % MULTIPLICITIES (per agent)
    mults = [0:15]; % multiplicity bins
    hist_g_mult_$agent = hist( g_mult_$agent, mults );
    f_mult_$agent = figure('position', [1000 100 1.5*[560 420]]);
    p_mult_$agent = stairs( mults, g_mult_$agent/length(g_mult_agent) ); % divide by length in order to normalize frequency for histogram
    ax_mult_$agent = gca;
    pwdir = $(pwd)
    TitStr_$agent = sprintf ( \"%s: Gamma Multiplicity for $agent\", pwdir );
    T_mult_$agent = title( TitStr_$agent );
    xl_mult_$agent = xlabel( 'Number of Gammas Produced at Capture' );
    %save (f_mult_$agent, 'f_mult_$agent.fig %.....png also.....syntax.....')
    %close f_mult_$agent % can enable once saving is decided


" >> ./plot_gammas.m

done



### plot total gamma energies
for agent_file in ./gam/*.gam; do
  
  agent=$(basename $agent_file .gam)
  
  echo "\
    % GAMMA ENERGIES (per agent)
    E = [0:.01:10]; % 10-keV energy bins
    hist_g_ke_$agent = hist( g_ke_$agent, E );
        
" >> ./plot_gammas.m



# all pau!   )
exit 0
