#!/bin/bash
# plot_gammas_mfile -- generate m-file for making total & agent-specific plots of gamma multiplicities & energy totals
# ~ Mark J. Duvall ~ mjduvall@hawaii.edu ~ August 2015 ~ #



## read in data
DATADIR=$(pwd)
DATARUN=$(basename $(pwd))
echo "\
  % plot_gammas -- generate histograms for gamma multiplicity & total energy (at capture) for each capturing agent
  % 	-- generated by ${BASH_SOURCE[0]} for $DATADIR/$DATARUN; $(date)
  
  
  %% TOTAL PLOTS
  % read in data & prepare histograms
  data = dlmread( '$DATARUN.txt', '', 1, 0 );
  g_mult = data(:,8);
  g_ke = data(:,9);
  mult = [0:15]; % multiplicity bins (0--15 by integers)
  h_g_mult = hist( g_mult, mult );
  E = [0:.01:10]; % 10-keV energy bins
  h_g_ke = hist( g_ke, E );
  
  % prepare figures:
  % multiplicity plot
  f_mult = figure('position', [1000 100 1.5*[560 420]]);
  ax_mult = axes;
  s_mult = stairs( mult, h_g_mult );
  xla_mult = xlabel('Multiplicity');
  T_mult = title('Gamma Multiplicities for $DATARUN', 'interpreter', 'none');
  % energy plot
  f_ke = figure('position', [1000 100 1.5*[560 420]]);
  ax_ke = axes('yscale', 'log');
  s_g_ke = stairs( E, h_g_ke + .01 ); % +.01 makes every count finite so ML will draw graph properly
  set(ax_ke, 'yscale', 'log')
  YL = get(ax_ke, 'ylim');
  ylim([10^0 YL(2)])
  xla_ke = xlabel('Energy (MeV)');
  T_ke = title('Total Energy of Capture Gammas for $DATARUN', 'interpreter', 'none');
  
  
" > ./plot_gammas.m



## get data for each capture agent
echo "%% INDIVIDUAL PLOTS" >> ./plot_gammas.m

for agent_file in ./gam/*.gam; do
  
  agent=$(basename $agent_file .gam | sed s/-/_minus/ | sed s/+/_plus/)
  
  echo "\
    % $agent plot
    % read in data
    data = dlmread( '$agent_file', '', 0, 1 );
    
    % create lists from data
    g_mult_$agent = data(:,1);   % can remove individual labels (& overwrite each time) if RAM becomes an issue
    g_ke_$agent = data(:,2);  % can remove individual labels (& overwrite each time) if RAM becomes an issue
%   clear data


" >> ./plot_gammas.m

done



## plot multiplicities
echo "\
    % MULTIPLICITIES (per agent)
    mults = [0:15]; % multiplicity bins
    f_mult_by_agent = figure('position', [1000 100 1.5*[560 420]]);
    ax_mult_by_agent = axes;
    T_mult_by_agent = title('Gamma Multiplicity', 'interpreter', 'none');
    xl_mult_by_agent = xlabel( 'Number of Gammas' );

    hold on

" >> ./plot_gammas.m

for agent_file in ./gam/*.gam; do
  
  agent=$(basename $agent_file .gam | sed s/-/_minus/ | sed s/+/_plus/)

  echo "\
    h_g_mult_$agent = hist( g_mult_$agent, mults );
    p_mult_$agent = stairs( mults, h_g_mult_$agent );
    %close f_mult_$agent % can enable once saving is decided

" >> ./plot_gammas.m

#    %save (f_mult_$agent, 'f_mult_$agent.fig %.....png also.....syntax.....')
#    %close %figure
done
echo



### plot total gamma energies
echo "\
    % GAMMA ENERGIES (per agent)
    E = [0:.01:10]; % 10-keV energy bins
    f_ke_by_agent = figure('position', [1000 100 1.5*[560 420]]);
    ax_ke_by_agent = axes;
    xl_ke_by_agent = xlabel('Energy (MeV)');
    T_ke_by_agent = title('Total Gamma-Capture Energy for $DATARUN', 'interpreter', 'none');
    
    hold on

" >> ./plot_gammas.m

for agent_file in ./gam/*.gam; do
  
  agent=$(basename $agent_file .gam | sed s/-/_minus/ | sed s/+/_plus/)
  
  echo "\
    % GAMMA ENERGIES (per agent)
    h_g_ke_$agent = hist( g_ke_$agent, E );
    p_ke_$agent = stairs( E, h_g_ke_$agent + .01 ); % +.01 makes every count finite so ML will draw graph properly
    
" >> ./plot_gammas.m

done

echo "\
set(ax_ke_by_agent, 'yscale', 'log');
YL = get(ax_ke_by_agent, 'ylim');
ylim([10^0 YL(2)])
" >> ./plot_gammas.m


# all pau!   )
exit 0
