#!/bin/bash
# ratsrc -- simple script to view the source files for a given RAT-PAC class
# ~ Mark J. Duvall ~ duvall3@github.com ~ 7/2021 ~ #
#
# USAGE: ratsrc <RATclass>


##Copyright (C) 2021 Mark J. Duvall
##
##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# arg check
if [[ ! $1 ]]; then
  echo -e "\nUSAGE: ratsrc <RATclass>"
  exit 10
fi

# init
HFILE_NAME="$1".hh
CFILE_NAME="$1".cc

# locate files
HFILE=$(find $RATROOT -name $HFILE_NAME | head -1)
CFILE=$(find $RATROOT -name $CFILE_NAME | head -1)
if [[ $HFILE ]]; then
  HFILE_TF=true
else
  HFILE_TF=false
  echo "Warning: Header file $HFILE_NAME not found."
fi
if [[ $CFILE ]]; then
  CFILE_TF=true
else
  CFILE_TF=false
  echo "Warning: Source file $CFILE_NAME not found."
fi
if (! $HFILE_TF) && (! $CFILE_TF); then
  echo "No .h or .cxx files for class \"$1\" found under $RATROOT. Searching src/..."
  GREPLIST=$(grep -iE -IRl $1 "$RATROOT"/src)
  if [[ $GREPLIST ]]; then
    echo -e "Mentions of \"$1\" found in the following files:\n"
    echo $GREPLIST | sed s@$RATROOT@'$RATROOT'@g | tr ' ' '\n'
    echo
    exit 2
  else
    echo -e "No mentions of \"$1\" found under $RATROOT/src. Exiting.\n"
    exit 3
  fi
fi

# open for reading only
vim -R -c ":set filetype+=.root" -c ":au BufNewFile,BufRead * set filetype+=.root" $HFILE $CFILE

# all pau!   )
exit 0
