#!/bin/bash
# ref_compare.sh -- workaround for ROOT crashes
# Usage: user@host:$RATROOT/data/<experiment>/.../REF_DISTRIBS$ ref_compare.sh <DIRECTORY> [VARNAME]
# ~ Mark J. Duvall ~ mjduvall@hawaii.edu ~ 10/2022 ~ #

#Copyright (C) 2022 Mark J. Duvall / T. Rocks Science
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# arg / help check
if [[ ($# -eq 0) || ($1 =~ -h) ]]; then
  echo "Usage: user@host:$RATROOT/data/<experiment>/.../REF_DISTRIBS$ ref_compare.sh <DIRECTORY> [VARNAME]"
  exit 10
fi

# init
TESTDIR=$1
VARNAME=${2:-phi}
OUTFILE=$TESTDIR"/ref_compare.txt"
echo -e "# $OUTFILE | generated by $USER @ $HOST in $(pwd) | $('date' -R)\n" > $OUTFILE

# main
for FILE in $TESTDIR/*_$VARNAME.root; do
  echo "root" >> $OUTFILE
  echo "TRefMatch *r = new TRefMatch(\"$FILE\");" >> $OUTFILE
  echo "r->Run();" >> $OUTFILE
  echo ".q" >> $OUTFILE
  echo >> $OUTFILE
done

# all pau!   )
echo -e "Commands-file written to $OUTFILE.\nPaste the contents into a terminal in the REF_DISTRIBS directory."
exit 0
