#!/bin/bash
# ref_compare.sh -- workaround for ROOT crashes
# Usage: user@host:$RATROOT/data/<experiment>/.../REF_DISTRIBS$ ref_compare.sh <DIRECTORY> [ANDERSON_TF=false] [VARNAME=phi]
# ~ Mark J. Duvall ~ mjduvall@hawaii.edu ~ 10/2022 ~ #

#Copyright (C) 2022 Mark J. Duvall / T. Rocks Science
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# arg / help check
if [[ ($# -eq 0) || ($1 =~ -h) ]]; then
  echo "Usage: user@host:$RATROOT/data/<experiment>/.../REF_DISTRIBS$ ref_compare.sh <DIRECTORY> [ANDERSON_TF=false] [VARNAME=phi]"
  exit 10
fi

# init
HOST=$(hostname)
DATE=$('date' -R)
TESTDIR=$1
ANDERSON_TF=${2:-kFALSE}
VARNAME=${3:-phi}
if [[ $TESTDIR =~ \/$ ]]; then TESTDIR=$(echo $TESTDIR | sed 's_\/$__'); fi
OUTFILE=$TESTDIR"/ref_compare.txt"
echo -e "# $OUTFILE\n# generated by $USER @ $HOST from $PWD\n# $DATE" > $OUTFILE

# main
for FILE in $TESTDIR/*_$VARNAME.root; do
  echo -n "
root
TRefMatch *r = new TRefMatch(\"$FILE\");
r->SetAnderson($ANDERSON_TF);
r->Run();
.q
" >> $OUTFILE
done
echo >> $OUTFILE

# all pau!   )
echo -e "Commands-file written to $OUTFILE\nPaste the contents into a terminal in the REF_DISTRIBS directory."
exit 0
