#!/bin/bash
# rootsrc -- simple script to view the source files for a given ROOT class
# ~ Mark J. Duvall ~ duvall3@github.com ~ 7/2021 ~ #
#
# USAGE: rootsrc <ROOTclass>


##Copyright (C) 2021 Mark J. Duvall
##
##    This program is free software: you can redistribute it and/or modify
##    it under the terms of the GNU General Public License as published by
##    the Free Software Foundation, either version 3 of the License, or
##    (at your option) any later version.
##
##    This program is distributed in the hope that it will be useful,
##    but WITHOUT ANY WARRANTY; without even the implied warranty of
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##    GNU General Public License for more details.
##
##    You should have received a copy of the GNU General Public License
##    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# help
usage() {
  echo -e "\nUSAGE: rootsrc [-h|-d] <ROOTclass>"
  echo -e "  -h\t\tShow this help message and exit"
  echo -e "  -d\t\tprint filenames and exit"
  echo
}

# arg check
if [[ ! $1 ]]; then
  usage
  exit 10
fi

# option(s)
PRINT_ONLY=false
while getopts ":hp" OPTIONS; do
  case $OPTIONS in
    h)
      usage
      exit 5
      ;;
    p)
      PRINT_ONLY=true
      ;;
    *)
      usage
      exit 10
      ;;
  esac
done
shift $((OPTIND-1))

# init
HFILE_NAME="$1".h
CFILE_NAME="$1".cxx

# locate files
HFILE=$(find $ROOTSYS -name $HFILE_NAME | head -1)
CFILE=$(find $ROOTSYS -name $CFILE_NAME | head -1)
if [[ $HFILE ]]; then
  HFILE_TF=true
else
  HFILE_TF=false
  echo "Warning: Header file $HFILE_NAME not found."
fi
if [[ $CFILE ]]; then
  CFILE_TF=true
else
  CFILE_TF=false
  echo "Warning: Source file $CFILE_NAME not found."
fi
if (! $HFILE_TF) && (! $CFILE_TF); then
  echo "Error: No .h or .cxx files for class \"$1\" found under $ROOTSYS. Searching for mentions..."
  GREPLIST=$(grep -iE -IRl $1 "$ROOTSYS" 2> /dev/null)
  if [[ $GREPLIST ]]; then
    echo -e "\nMentions of \"$1\" found in the following files:\n"
    echo $GREPLIST | sed s@$ROOTSYS@'$ROOTSYS'@g | tr ' ' '\n'
    echo
    exit 2
  else
    echo -e "No mentions of \"$1\" found under $ROOTSYS/src. Exiting.\n"
    exit 3
  fi
fi

# main
# echo -e "<$1> Files:\n$HFILE\n$CFILE"
echo -e "$HFILE\n$CFILE"
if $PRINT_ONLY; then
  exit 0
else
  # open for reading only
  vim -R -c ":set filetype+=.root" -c ":au BufNewFile,BufRead * set filetype+=.root" -p $HFILE $CFILE
fi

# all pau!   )
exit 0
