/********************************************************************
* duvallanalyze.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error duvallanalyze.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableduvallanalyze();
extern void G__cpp_setup_inheritanceduvallanalyze();
extern void G__cpp_setup_typetableduvallanalyze();
extern void G__cpp_setup_memvarduvallanalyze();
extern void G__cpp_setup_globalduvallanalyze();
extern void G__cpp_setup_memfuncduvallanalyze();
extern void G__cpp_setup_funcduvallanalyze();
extern void G__set_cpp_environmentduvallanalyze();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TDuvallAnalyze.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__duvallanalyzeLN_TClass;
extern G__linked_taginfo G__duvallanalyzeLN_TBuffer;
extern G__linked_taginfo G__duvallanalyzeLN_TMemberInspector;
extern G__linked_taginfo G__duvallanalyzeLN_TObject;
extern G__linked_taginfo G__duvallanalyzeLN_TNamed;
extern G__linked_taginfo G__duvallanalyzeLN_TString;
extern G__linked_taginfo G__duvallanalyzeLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__duvallanalyzeLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__duvallanalyzeLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__duvallanalyzeLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__duvallanalyzeLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__duvallanalyzeLN_TFile;
extern G__linked_taginfo G__duvallanalyzeLN_TDuvallAnalyze;

/* STUB derived class for protected member access */
