#!/bin/bash
# makedocs -- compile and (optionally) update documentation for 'Tools for Reactor-Antineutrino Studies in RAT-PAC'
# USAGE: makedocs [-h|-u] 
# ~ Mark J. Duvall ~ duvall3.git@gmail.com ~ 06/2023 ~ #

# Copyright (C) 2023 Mark J. Duvall / T. Rocks Science
# 
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 


## INIT

# general
NULL=/dev/null
ERR=/dev/stderr

# control for aliases
ECHO="$(which echo) -e"

# define usage
usage() {
  $ECHO "Usage: makedocs [-h|-u] "
  $ECHO "compile and (optionally) update documentation for 'Tools for Reactor-Antineutrino Studies in RAT-PAC'"
  $ECHO
  $ECHO "Options:"
  $ECHO "  -h\tShow this help message and exit"
  $ECHO "  -u\tUpdate doc files on uhunix"
  $ECHO
}

# process options
SEND_UPDATE=false
while getopts "hu" OPTIONS; do
  case $OPTIONS in
    h)
      usage
      exit 10
      ;;
    u)
      SEND_UPDATE=true
      ;;
    *)
      $ECHO
      usage
      exit 11
      ;;
  esac
done
# shift $((OPTIND-1)) # uncomment for options with args


## MAIN

# run doxygen
doxygen Doxyfile

# un-convert certain html sequences in doxygen's output
FILE_LIST=( doc/html/{md_README,md_ReferenceMatching}.html )
for FILE in ${FILE_LIST[*]}; do
  vim $FILE -c ":call FixDoxyChars()" -c ":wq"
done

# update if indicated
UHU_DIR=$HOME/uhunix/public_html
if $SEND_UPDATE; then
  echo "Updating doc files on Web server..."
  cd $UHU_DIR
  ./update_rattools_doc.sh
  if [ $? -eq 0 ]; then echo "Done."; fi
  cd - > $NULL
fi


## EXIT

# all pau!   )
EXIT_STATUS=${EXIT_STATUS:-0}
if [ $EXIT_STATUS -eq 0 ]; then
  echo -e "\nSuccess!"
else
  echo -e "\nExiting with error(s)."
fi
exit $EXIT_STATUS

