# ibd.mac -- IBD generator for SANTA-style experiment
#	-- uses altered IBD.ratdb

#/generator/add combo ibd:fill:poisson
/generator/add combo ibd:regexfill:poisson
#/generator/add combo ibd:point:poisson
/generator/vtx/set -1 0 0 # neutrinos directed along -x direction
#/generator/vtx/set 0 0 1
#/generator/pos/set 0 -9000 -500
#/generator/pos/set target_plane
/generator/pos/set target_bar
#/generator/pos/set capture_bar #debug
#/generator/pos/set 500 0 0
#/generator/rate/set 1
/generator/rate/set 1.23e-6	// mTC@NIST parameters

# off-axis tests, such that phi_source_true = {15,30,45} deg
#/generator/vtx/set -0.9659258262890683 -0.2588190451025207 0 # neutrinos angled 15 deg from the -x direction
#/generator/vtx/set -0.8660254037844387 -0.4999999999999999 0 # neutrinos angled 30 deg from the -x direction
#/generator/vtx/set -0.7071067811865476 -0.7071067811865475 0 # neutrinos angled 45 deg from the -x direction
