/control/execute init.mac
/control/execute vis.mac
#/control/execute gen/ibd.mac
/control/execute gen/mu.mac
/control/shell echo "REMINDER: Set output filename before starting run!"
/control/shell echo
/control/shell echo "rEmInDeR: CAPTURE PLANE STILL DOPED WITH GADOLINIUM, NOT BORON!!!!!!!"
/control/shell echo

#/tracking/storeTrajectory 1
#/tracking/storeParticleTrajectory anti_nu_e
### USE e+ LOCATION(s) OR n0 START LOCATION AS VERTEX?? ###
#/tracking/storeParticleTrajectory e+
#/tracking/storeParticleTrajectory neutron
/tracking/storeParticleTrajectory mu-
