# init -- set & initialize experiment

/glg4debug/glg4param omit_muon_processes 0
/glg4debug/glg4param omit_hadronic_processes 0

/rat/db/set DETECTOR experiment "santa_fov"
/rat/db/set DETECTOR geo_file "santa_fov/santa_fov.geo"
#/rat/db/set DETECTOR experiment "santa_fov_2D"
#/rat/db/set DETECTOR geo_file "santa_fov/santa_fov_2D.geo"
#/rat/db/set DETECTOR experiment "santa_fov_3D"
#/rat/db/set DETECTOR geo_file "santa_fov/santa_fov_3D.geo"

#/rat/db/load ./IBD.ratdb
#/rat/db/load ./MATERIALS_Watchman.ratdb
#/rat/db/load ./MATERIALS_test.ratdb
#/rat/db/load ./OPTICS_test.ratdb

/run/numberOfThreads 4
/run/initialize

/rat/proc fitcentroid
#/rat/proc fitpath
/rat/proc count
/rat/procset update 100
/rat/proclast outroot

#/rat/proc prune
#/rat/procset prune "mc.track:opticalphoton"
