# Macro file for the visualization setting in the initialization phase 
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGLIQt 1000x1000-0+0
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume

/vis/viewer/set/background white

# Set upward direction to z-axis:
/vis/viewer/set/upVector 0 0 1
#
# Specify view angle:
/vis/viewer/set/viewpointVector .5 .1 .3
/vis/viewer/set/lightsVector .4 .9 .6
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style w
#/vis/viewer/set/style s
/vis/viewer/set/hiddenEdge true
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100

# Axes, scale, etc.
/vis/set/textSize 18.0
#/vis/scene/add/axes/g 0 -9.45 -2 1 m grey false # Simple axes: x=red, y=green, z=blue.
#/vis/scene/add/date    # Date stamp
# for full view:
# 764 x 764 x 764 mm^3
#/vis/scene/add/scale 764 mm x 0. 0. 0. manual 0. 410. 410. mm
#/vis/scene/add/scale 764 mm y 0. 0. 0. manual -410. 0. 410. mm
#/vis/scene/add/scale 764 mm z 0. 0. 0. manual 410. 410. 0. mm

## SPECIAL SETTINGS for highlighting lattice structure
/vis/viewer/zoomTo 7
/vis/viewer/set/targetPoint 0. 0. 0. m
/vis/viewer/set/viewpointThetaPhi 70. -10.
/vis/geometry/set/visibility target_cell_array 1 1
/vis/geometry/set/visibility target_cell_array 0 0
/vis/viewer/set/hiddenEdge false
/vis/geometry/set/colour target_cell_array 1 0.8 0.8 0.8 0.2
/vis/geometry/set/colour target_cell_7_7_7 0 black 0.5
/vis/geometry/set/colour target_cell_6_6_6 0 black 0.5
/vis/geometry/set/colour target_cell_6_6_8 0 black 0.5
/vis/geometry/set/colour target_cell_6_8_6 0 black 0.5
/vis/geometry/set/colour target_cell_6_8_8 0 black 0.5
/vis/geometry/set/colour target_cell_8_6_6 0 black 0.5
/vis/geometry/set/colour target_cell_8_6_8 0 black 0.5
/vis/geometry/set/colour target_cell_8_8_6 0 black 0.5
/vis/geometry/set/colour target_cell_8_8_8 0 black 0.5
# for solid version:
#/vis/viewer/set/style s
#/vis/viewer/set/hiddenEdge true
#/vis/geometry/set/visibility target_cell_array 1 0
#/vis/geometry/set/visibility target_cell_6_6_6 0 1
#/vis/geometry/set/visibility target_cell_6_6_7 0 1
#/vis/geometry/set/visibility target_cell_6_6_8 0 1
#/vis/geometry/set/visibility target_cell_6_7_6 0 1
#/vis/geometry/set/visibility target_cell_6_7_7 0 1
#/vis/geometry/set/visibility target_cell_6_7_8 0 1
#/vis/geometry/set/visibility target_cell_6_8_6 0 1
#/vis/geometry/set/visibility target_cell_6_8_7 0 1
#/vis/geometry/set/visibility target_cell_6_8_8 0 1
#/vis/geometry/set/visibility target_cell_7_6_6 0 1
#/vis/geometry/set/visibility target_cell_7_6_7 0 1
#/vis/geometry/set/visibility target_cell_7_6_8 0 1
#/vis/geometry/set/visibility target_cell_7_7_6 0 1
#/vis/geometry/set/visibility target_cell_7_7_7 0 1
#/vis/geometry/set/visibility target_cell_7_7_8 0 1
#/vis/geometry/set/visibility target_cell_7_8_6 0 1
#/vis/geometry/set/visibility target_cell_7_8_7 0 1
#/vis/geometry/set/visibility target_cell_7_8_8 0 1
#/vis/geometry/set/visibility target_cell_8_6_6 0 1
#/vis/geometry/set/visibility target_cell_8_6_7 0 1
#/vis/geometry/set/visibility target_cell_8_6_8 0 1
#/vis/geometry/set/visibility target_cell_8_7_6 0 1
#/vis/geometry/set/visibility target_cell_8_7_7 0 1
#/vis/geometry/set/visibility target_cell_8_7_8 0 1
#/vis/geometry/set/visibility target_cell_8_8_6 0 1
#/vis/geometry/set/visibility target_cell_8_8_7 0 1
#/vis/geometry/set/visibility target_cell_8_8_8 0 1

# To get nice view
#/vis/geometry/set/visibility world 0 false
#/vis/viewer/pan 0 -9 m

# set or correct volume properties:
#/vis/geometry/set/colour world 0 .6 .2 .1 .1
/vis/geometry/set/visibility world 0 0
/vis/geometry/set/visibility cave 0 0
#/vis/geometry/set/colour target_cell_array 1 0. 0. 0.
#/vis/geometry/set/visibility target_cell_array 1 0
#/vis/geometry/set/visibility target_cell_array 0 1
#/vis/geometry/set/colour target_cell_array 0 0. 0. 0.
#/vis/geometry/set/colour cave 0 0 0 0 .2
#/vis/geometry/set/colour cave_floor 0 .6 .2 .1 .3
#/vis/geometry/set/colour cave_ceiling 0 .6 .2 .1 .3
#/vis/geometry/set/colour cave_back 0 .6 .2 .1 .3
#/vis/geometry/set/colour cave_lwall 0 .6 .2 .1 .3
#/vis/geometry/set/colour cave_rwall 0 .6 .2 .1 .3
#/vis/geometry/set/colour target_cell_array 1 .2 0 1
#/vis/geometry/set/colour target_cell_array 1 grey

/vis/viewer/set/hiddenMarker true
#/vis/viewer/set/targetPoint 0 -9 0 m

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
# Draw by charge:
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# Or, draw by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParcticleID-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByParcticleID-0/default/setStepPtsSize 2
#
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits

# accumulate event:
/vis/scene/endOfEventAction accumulate
