#!/bin/bash
# chain_ncap -- generate a ROOT macro to combine all the neutronCaptures TTrees
# -- intended for use with github.com/duvall3/rat-pac/tree/collab/user/shell_scripts/local_batch_jobs.sh
#		       and 					"	            /duvall3analyze.sh
# Usage:
# 1) Run this script in the umbrella directory of your datarun
# 2) [Optional] Run duvall3analyze.sh
# ~ Mark J. Duvall ~ mjduvall@hawaii.edu ~ 06/2022 ~ #

#Copyright (C) 2022 Mark J. Duvall / T. Rocks Science
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


# init
DATARUN_AUTO=$(basename $(pwd))
DATARUN=${1:-$DATARUN_AUTO}
OUTFILE="$DATARUN"_ncap.root

# create chain_ncap.cxx
echo -e "\
// chain_ncap.cxx -- combine TChains
// -- for use with SimpleEnergyDAQ from \$RATROOT/user/root_macros/SEDAQ2.cxx
// -- USAGE: open ROOT and run \".x ./chain_ncap.cxx\"
// Mark J. Duvall ~ mjduvall@hawaii.edu ~ 06/2022 ~ //
// Generated by user $USER on host $HOSTNAME at $(date -R)\n
void chain_ncap() {\n
// init
TChain ch(\"T_ncap\");\n\n// file loop\n" > chain_ncap.cxx

# add individual runs
for DIR in $DATARUN*/; do
  FILE_BASE=$(basename $DIR /)
  FILE_PREFIX="$FILE_BASE/$FILE_BASE"
  FILENAME=$FILE_PREFIX"_ncap.root"
  echo "\
ch.Add(\"$FILE_BASE/$FILENAME\");"  >> chain_ncap.cxx
done

# prepare merging and saving
echo -e "\n\
// merge trees
ch.Merge(\"$OUTFILE\");\n
//all pau!   )
}" >> chain_ncap.cxx

# run the newly-created macro
root -q -l -b 'chain_ncap.cxx()'

# copy database into output file (can use last datarun file)
FILENAME=$FILE_PREFIX".root"
CPCMD="rootcp $FILE_BASE/$FILENAME:db $OUTFILE:db"
# echo $CPCMD #debug
eval $CPCMD
# echo -e "rootcp exit status: $?" #debug

# all pau!  )
exit 0
