#!/bin/bash
# chain_ref -- generate a ROOT macro to combine multiple reference runs
# -- intended for use with the TRefMatch system in this repository
# -- REMINDER: Clear outfiles BEFORE RUNNING or their entries
#      will be duplicated
# -- Run this script in the umbrella directory of your datarun
# Usage: chain_ref.sh <MAXVAL> [MINVAL] [PATTERN]
# ~ Mark J. Duvall ~ mjduvall@hawaii.edu ~ 09/2022 ~ #

#Copyright (C) 2022 Mark J. Duvall / T. Rocks Science
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

# arg check
if [[ ($# -eq 0) || ($1 =~ -h) ]]; then
  echo "USAGE: chain_ref.sh <MAXVAL> [MINVAL] [PATTERN]"
  exit 10
fi

# init
MAXVAL=$1
MINVAL=${2:-0}
PATTERN=${3:-"%02dDEG_ref.root"}
for (( k=$MINVAL; k<=$MAXVAL; k++ )) {
  TARGETS[k]=$(printf $PATTERN $k)
}

##debug
#for (( k=$MINVAL; k<=$MAXVAL; k++ )) {
#  echo ${TARGETS[$k]}
#}


# MAIN
for (( k=$MINVAL; k<=$MAXVAL; k++ )) {

  OUTFILE=${TARGETS[$k]}
  OUTSCRIPT=$(printf "chain_ref_%02d.cxx" $k)

  # create outscript
  echo -e "\
  // $OUTSCRIPT -- combine TChains
  // Mark J. Duvall ~ mjduvall@hawaii.edu ~ 09/2022 ~ //
  // Generated by user $USER on host $HOSTNAME at $(date -R)\n
  void $(basename $OUTSCRIPT .cxx)() {\n
  // init
  TChain ch(\"T\");\n\n  // file entries" > $OUTSCRIPT

  # add individual runs
  SOURCEFILES=($(find -name $OUTFILE))
  for FILE in ${SOURCEFILES[*]}; do
    # echo $FILE #debug
    echo "  ch.Add(\"$FILE\");"  >> $OUTSCRIPT
  done

  # prepare merging and saving
  echo -e "\n\
  // merge trees
  ch.Merge(\"$OUTFILE\");" >> $OUTSCRIPT

  # copy objects
  echo -e "\n\
  // copy needed objects into ref file
  TFile *f_source = TFile::Open(\"${SOURCEFILES[0]}\");
  TVectorD *phiTrue = (TVectorD*)gDirectory->Get(\"phiTrue\");
  TFile *f = TFile::Open(\"$OUTFILE\", \"update\");
  phiTrue->Write(\"phiTrue\");
  f->Close();
  f_source->Close();\n
  //all pau!   )
  }" >> $OUTSCRIPT

  # # run the newly-created macro
  ROOTCMD="root -q -l -b '$OUTSCRIPT()'"
  # echo $ROOTCMD #debug
  eval $ROOTCMD

}

# clean up
CHAINDIR="chain_ref_macros"
if [ -d $CHAINDIR ]; then
  /usr/bin/rm $CHAINDIR/*.cxx
else
  mkdir $CHAINDIR
fi
mv -t $CHAINDIR chain_ref*.cxx

# all pau!  )
exit 0
